# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Copy only package info first
COPY package*.json ./

# Install dependencies (for live reload)
RUN npm install

# Copy public folder (required for react-scripts)
COPY public ./public

# Do NOT copy src; it will be mounted as a volume for hot reload
EXPOSE 3000

# Start React dev server (with hot reload)
CMD ["npm", "start"]
